#  Evaluating model performance

In [ ]:
# It is performed when there is an option to choose multiple algorithms and we select the best one on the basis of performance

In [ ]:
# Eg - We can use svm,random forest,decision tree on iris flower, but we find which one is best

In [ ]:
# Ways to perform this observation

In [ ]:
# 1. Use all available data for training and test on same dataset
# -> Results in overfitting the model -> which makes model performed bad on newer data or variation

In [ ]:
# 2. Use train-test split in data
# -> Using different sections of data as train and tests again and again, and get average of score

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [27]:
from sklearn.datasets import load_iris

In [28]:
iris = load_iris()

In [29]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size = 0.3)

In [32]:
LR = LogisticRegression(multi_class = 'auto',solver='liblinear')
LR.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
LR.score(X_test,y_test)

0.9111111111111111

In [34]:
SV = SVC(gamma=4)
SV.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=4, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [35]:
SV.score(X_test,y_test)

0.9777777777777777

In [36]:
RFC = RandomForestClassifier(n_estimators = 50)
RFC.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [37]:
RFC.score(X_test,y_test)

0.9111111111111111

In [38]:
from sklearn.model_selection import KFold

In [39]:
k = KFold(n_splits = 3) #n_split indicates how many folds you want (train-test split 3 times inside the data)
k

KFold(n_splits=3, random_state=None, shuffle=False)

In [40]:
# Eg - 
#for train_index,test_index in k.split([1,2,3,4,5,6,7,8,9]):
#    print(train_index,test_index) # train sample and test sample get changed again and again for the same data

In [41]:
# function method
def getscore(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [42]:
getscore(LogisticRegression(),X_train,X_test,y_train,y_test)

0.9111111111111111

In [43]:
getscore(SVC(),X_train,X_test,y_train,y_test)

0.9777777777777777

In [44]:
getscore(RandomForestClassifier(n_estimators = 40),X_train,X_test,y_train,y_test)

0.9111111111111111

In [45]:
from sklearn.model_selection import StratifiedKFold
# StratifiedKFold is little better than KFold in sense it divides train tests more uniformly

In [46]:
SKF = StratifiedKFold(n_splits = 3)

In [55]:
scores_LR = []
scores_SV = []
scores_RFC = []
for train_index, test_index in SKF.split(iris.data,iris.target):
    X_train,X_test,y_train,y_test = iris.data[train_index],iris.data[test_index], \
                                    iris.target[train_index],iris.target[test_index]
    scores_LR.append(getscore(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_SV.append(getscore(SVC(),X_train,X_test,y_train,y_test))
    scores_RFC.append(getscore(RandomForestClassifier(),X_train,X_test,y_train,y_test))

In [56]:
scores_LR

[0.9607843137254902, 0.9215686274509803, 0.9583333333333334]

In [57]:
scores_SV

[0.9803921568627451, 0.9607843137254902, 0.9791666666666666]

In [58]:
scores_RFC

[0.9803921568627451, 0.9019607843137255, 0.9791666666666666]

In [59]:
# Cross_Val Score Method

In [60]:
from sklearn.model_selection import cross_val_score

In [65]:
L_score = cross_val_score(LogisticRegression(),iris.data,iris.target)
L_score

array([0.96078431, 0.92156863, 0.95833333])

In [67]:
np.average(L_score)

0.9468954248366014

In [68]:
S_score = cross_val_score(SVC(),iris.data,iris.target)
S_score

array([0.98039216, 0.96078431, 0.97916667])

In [69]:
np.average(S_score)

0.9734477124183006

In [70]:
R_score = cross_val_score(RandomForestClassifier(n_estimators = 40),iris.data,iris.target)
R_score

array([0.98039216, 0.92156863, 0.97916667])

In [71]:
np.average(R_score)

0.960375816993464

In [ ]:
# SVM's average is highest, therefore SVM is the best model among these 3