In [ ]:
import numpy as np # numpy is faster, uses less memory and covenient than python list
# numpy is n dimentional matrix

In [4]:
l1 = [1,2,3,4,5]
l2 = [2,3,4,5,6]
list(zip (l1,l2))

[(1, 2), (2, 3), (3, 4), (4, 5), (5, 6)]

In [10]:
# less memory
import numpy as np
import time
import sys
l1 = (list(range(1000)))
print(sys.getsizeof(999)*len(l1))
a1 = np.arange(1000)
print(a1.size*a1.itemsize)

28000
4000


In [11]:
# fast
import time
size = 100000
l1 = list(range(size))
l2 = list(range(size))

a1 = np.arange(size)
a2 = np.arange(size)

start_time_for_list = time.time()
l3 = [(x+y) for x,y in zip(l1,l2)] #[l1[i] + l2[i] for i in range(len(l1))]
end_time = time.time()
print((end_time - start_time_for_list)*1000)
start_time_for_array = time.time()
a3 = a1 + a2
end_time_arr = time.time()
print((end_time_arr - start_time_for_array)*1000)
print(a3)

10.509014129638672
1.0013580322265625
[     0      2      4 ... 199994 199996 199998]


In [14]:
#sum of 2 arrays(1 dimentional) #numpy does matrix addition whereas list1 + list2 just concates the two lists
import numpy as np
size = 10
a1 = np.arange(size)
print(a1)
a2 = np.arange(size)
print(a2)
a3 = a1 + a2
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [16]:
a = np.array([12,34,5,4]) # user defined elements in a list instead of range
print(a.ndim) #prints dimention of the array
print(a[2])

1
5


In [19]:
a = np.array([[1,2],[3,4],[5,6]]) 
print(a)
print(a.ndim)

#list method
li = [[1,2],[3,4],[5,6]]
print(li)

[[1 2]
 [3 4]
 [5 6]]
2
[[1, 2], [3, 4], [5, 6]]


In [20]:
a.itemsize #size of an item(tells space taken by an item)

4

In [22]:
a.dtype

dtype('int32')

In [23]:
a = np.array([[1,2],[3,4],[5,6]],dtype = np.float)
print(a.dtype)
a

float64


array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [34]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
print(a) #print command prints the final value of a variable

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [36]:
a.size

20

In [37]:
a.shape

(4, 5)

In [2]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]],dtype = complex)
print(a.ndim)
a

2


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [42]:
a = np.array([[[2,3],
             [4,5]],
            [[6,7],
             [8,9]]])
print(a)
print(a.ndim)
#a

[[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]
3


In [3]:
a = np.zeros((2,2,3,3)) # 1 dimentional = 3*2*2, 2 dimentional = 2*2, 3 dimentional = 2, 4 dimentional =1
print(a.ndim)
print(a)

4
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]


In [5]:
np.ones((2,6),dtype = bool)

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [8]:
np.diag([2,3,4,5])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [51]:
a = np.arange(2,20,3)
a

array([ 2,  5,  8, 11, 14, 17])

In [54]:
# linear space functions (makes elements between a no, e.g= from 1->16 make 10 elements)
a = np.linspace(1,16,10,retstep = True) # retstep tells difference between the element's value
a

(array([ 1.        ,  2.66666667,  4.33333333,  6.        ,  7.66666667,
         9.33333333, 11.        , 12.66666667, 14.33333333, 16.        ]),
 1.6666666666666667)

In [57]:
a = np.linspace([10,20,30],[16,4,5],10, dtype = int, axis = -1, retstep = True) #axis = -1 (for columns)
print(a)

(array([[10, 10, 11, 12, 12, 13, 14, 14, 15, 16],
       [20, 18, 16, 14, 12, 11,  9,  7,  5,  4],
       [30, 27, 24, 21, 18, 16, 13, 10,  7,  5]]), array([ 0.66666667, -1.77777778, -2.77777778]))


In [104]:
a = np.linspace([10,20,30],[16,4,5],10, dtype = int, axis = 0, retstep = True) #axis = 0 (for rows)
print(a)

(array([[10, 20, 30],
       [10, 18, 27],
       [11, 16, 24],
       [12, 14, 21],
       [12, 12, 18],
       [13, 11, 16],
       [14,  9, 13],
       [14,  7, 10],
       [15,  5,  7],
       [16,  4,  5]]), array([ 0.66666667, -1.77777778, -2.77777778]))


In [88]:
import numpy as np
a =np.arange(48).reshape(4,2,6)
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [5]:
import numpy as np
a = np.arange(500,620).reshape(2,3,4,5)
a

array([[[[500, 501, 502, 503, 504],
         [505, 506, 507, 508, 509],
         [510, 511, 512, 513, 514],
         [515, 516, 517, 518, 519]],

        [[520, 521, 522, 523, 524],
         [525, 526, 527, 528, 529],
         [530, 531, 532, 533, 534],
         [535, 536, 537, 538, 539]],

        [[540, 541, 542, 543, 544],
         [545, 546, 547, 548, 549],
         [550, 551, 552, 553, 554],
         [555, 556, 557, 558, 559]]],


       [[[560, 561, 562, 563, 564],
         [565, 566, 567, 568, 569],
         [570, 571, 572, 573, 574],
         [575, 576, 577, 578, 579]],

        [[580, 581, 582, 583, 584],
         [585, 586, 587, 588, 589],
         [590, 591, 592, 593, 594],
         [595, 596, 597, 598, 599]],

        [[600, 601, 602, 603, 604],
         [605, 606, 607, 608, 609],
         [610, 611, 612, 613, 614],
         [615, 616, 617, 618, 619]]]])

In [6]:
a = np.linspace(100,400,120, dtype = int).reshape(2,3,4,5)
a

array([[[[100, 102, 105, 107, 110],
         [112, 115, 117, 120, 122],
         [125, 127, 130, 132, 135],
         [137, 140, 142, 145, 147]],

        [[150, 152, 155, 157, 160],
         [163, 165, 168, 170, 173],
         [175, 178, 180, 183, 185],
         [188, 190, 193, 195, 198]],

        [[200, 203, 205, 208, 210],
         [213, 215, 218, 221, 223],
         [226, 228, 231, 233, 236],
         [238, 241, 243, 246, 248]]],


       [[[251, 253, 256, 258, 261],
         [263, 266, 268, 271, 273],
         [276, 278, 281, 284, 286],
         [289, 291, 294, 296, 299]],

        [[301, 304, 306, 309, 311],
         [314, 316, 319, 321, 324],
         [326, 329, 331, 334, 336],
         [339, 342, 344, 347, 349]],

        [[352, 354, 357, 359, 362],
         [364, 367, 369, 372, 374],
         [377, 379, 382, 384, 387],
         [389, 392, 394, 397, 400]]]])

In [7]:
#ravel converts multidimentional array into a single list
b = a.ravel()
b

array([100, 102, 105, 107, 110, 112, 115, 117, 120, 122, 125, 127, 130,
       132, 135, 137, 140, 142, 145, 147, 150, 152, 155, 157, 160, 163,
       165, 168, 170, 173, 175, 178, 180, 183, 185, 188, 190, 193, 195,
       198, 200, 203, 205, 208, 210, 213, 215, 218, 221, 223, 226, 228,
       231, 233, 236, 238, 241, 243, 246, 248, 251, 253, 256, 258, 261,
       263, 266, 268, 271, 273, 276, 278, 281, 284, 286, 289, 291, 294,
       296, 299, 301, 304, 306, 309, 311, 314, 316, 319, 321, 324, 326,
       329, 331, 334, 336, 339, 342, 344, 347, 349, 352, 354, 357, 359,
       362, 364, 367, 369, 372, 374, 377, 379, 382, 384, 387, 389, 392,
       394, 397, 400])

In [8]:
a = np.array((1,2,3))
print(a)

[1 2 3]


In [9]:
a = np.array([(1,2,3),(3,4,5,6)])
a

array([(1, 2, 3), (3, 4, 5, 6)], dtype=object)

In [10]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
a

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a[1][3]

8

In [12]:
a = np.array([['sss',2,3],[5,6,7]])
print(a)

[['sss' '2' '3']
 ['5' '6' '7']]


In [13]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
a[1][2]

7

In [15]:
a[:2,:2]

array([[0, 1],
       [5, 6]])

In [16]:
a[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14]])

In [17]:
a[1:4,::3]

array([[ 5,  8],
       [10, 13],
       [15, 18]])

In [18]:
a[::4]

array([[0, 1, 2, 3, 4]])

In [19]:
a[3:4:2,::-2]

array([[19, 17, 15]])

In [20]:
a[3:4:-1,::2]

array([], shape=(0, 3), dtype=int32)

In [21]:
a[3:0:-1,::2]

array([[15, 17, 19],
       [10, 12, 14],
       [ 5,  7,  9]])

In [22]:
a[::-2,::-2]

array([[19, 17, 15],
       [ 9,  7,  5]])

In [23]:
a = [1,2,3,4,5]
b = a[::2]
b[1]='ss'
print(a,b)

[1, 2, 3, 4, 5] [1, 'ss', 5]


In [24]:
a = np.arange(20).reshape(4,5)
print(a)
print()
b = a[::2,::2]
print(b)
print() #updation of value takes place when slicing is done
b[1] = 100
print(b)
print()
print(a) #array updates the previous value too because it changes the value in the memory address unlike in lists which
            # does not change

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 0  2  4]
 [10 12 14]]

[[  0   2   4]
 [100 100 100]]

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [100  11 100  13 100]
 [ 15  16  17  18  19]]


In [25]:
# add 1 to each element
a = np.array([[1,2],[3,4]])
print(a)
b = a+1
c = a+b
print(c)
b

[[1 2]
 [3 4]]
[[3 5]
 [7 9]]


array([[2, 3],
       [4, 5]])

In [26]:
a = [3,4,5,6]
b = [3,4,5,6]
a is b #elements may be same, but address is different

False

In [27]:
x = np.arange(20).reshape(4,5)
sum = x.sum()
sum

190

In [28]:
a = np.arange(20).reshape(5,4)
a = a[a%2==0]
print(a)
a.mean()

[ 0  2  4  6  8 10 12 14 16 18]


9.0

In [29]:
a = np.arange(10,20).reshape(2,5)
print(a[a%2==0].sum())
print(a[a%2!=0].sum())

70
75


In [31]:
#square root of an array
import numpy as np
a = [9,4,36,49,100]
np.sqrt(a)

array([ 3.,  2.,  6.,  7., 10.])

In [33]:
a = np.arange(20).reshape(5,4)
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894]])

In [36]:
#standard deviation of an array (diffrence of values from mean)
import numpy as np
x = np.arange(10).reshape(2,5)
print(x)
np.std(x) #do a program using fuctions calculate square root

[[0 1 2 3 4]
 [5 6 7 8 9]]


2.8722813232690143

In [39]:
import numpy as np
a = np.array([[2,3],[5,6]])
b = np.array([[2,5],[5,9]])
print(a)
print()
print(b)
print()
print(a+b)
print()
print(a-b)
print()
print(a/b)
print()
print(a*b)

[[2 3]
 [5 6]]

[[2 5]
 [5 9]]

[[ 4  8]
 [10 15]]

[[ 0 -2]
 [ 0 -3]]

[[1.         0.6       ]
 [1.         0.66666667]]

[[ 4 15]
 [25 54]]


In [40]:
#dot product or matrix multiplication
a.dot(b)

array([[19, 37],
       [40, 79]])

In [43]:
a = np.array([2,3,4]) #mutilplication and addition of arrays can take place in numpy even if their orders are diffrent
print(a)
print()
b = np.arange(6).reshape(2,3)
print(b)
print()
print(a+b)
print()
print(a*b)

[2 3 4]

[[0 1 2]
 [3 4 5]]

[[2 4 6]
 [5 7 9]]

[[ 0  3  8]
 [ 6 12 20]]


In [44]:
a = np.array([[2],
              [3],
              [4],
              [5]])
for i in a:
    for j in i:
        print(j)

2
3
4
5


In [50]:
a = np.array([[2],
              [3],
              [4],
              [5]])
for i in a.flat:
    print(i)

2
3
4
5


In [51]:
a = np.array([[2],
              [3],
              [4],
              [5]])
a.ravel()

array([2, 3, 4, 5])

In [54]:
# stacking
#it takes place between arrays of same order
a = np.arange(6).reshape(3,2)
print(a)
print('_________')
b = np.arange(6,12).reshape(3,2)
print(b)
print('_________')
np.vstack((a,b)) #vstack takes place in arrays with same number of columns

[[0 1]
 [2 3]
 [4 5]]
_________
[[ 6  7]
 [ 8  9]
 [10 11]]
_________


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [55]:
a = np.arange(6).reshape(3,2)
print(a)
print('_________')
b = np.arange(6,12).reshape(3,2)
print(b)
print('_________')
np.hstack((a,b)) #hstack takes place in arrays with same number of rows

[[0 1]
 [2 3]
 [4 5]]
_________
[[ 6  7]
 [ 8  9]
 [10 11]]
_________


array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [61]:
#splitting arrays
#dividing array into multiple arrays
a = np.arange(15,45).reshape(5,6)
print(a)
print()
np.hsplit(a,3) #divides the parent array in to number of parts(in this eg, 3) according to rows

[[15 16 17 18 19 20]
 [21 22 23 24 25 26]
 [27 28 29 30 31 32]
 [33 34 35 36 37 38]
 [39 40 41 42 43 44]]



[array([[15, 16],
        [21, 22],
        [27, 28],
        [33, 34],
        [39, 40]]), array([[17, 18],
        [23, 24],
        [29, 30],
        [35, 36],
        [41, 42]]), array([[19, 20],
        [25, 26],
        [31, 32],
        [37, 38],
        [43, 44]])]

In [63]:
a = np.arange(15,51).reshape(6,6)
print(a)
print()
np.vsplit(a,3) #divides the parent array in to number of parts(in this eg, 3) according to columns

[[15 16 17 18 19 20]
 [21 22 23 24 25 26]
 [27 28 29 30 31 32]
 [33 34 35 36 37 38]
 [39 40 41 42 43 44]
 [45 46 47 48 49 50]]



[array([[15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26]]), array([[27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38]]), array([[39, 40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49, 50]])]

In [64]:
a = np.arange(12).reshape(3,4) #check condition with each element and return booloean
b = a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [67]:
a = np.arange(12).reshape(3,4) #checks condition with each element and return the value satisfying the condition
b = a[a>4]
b

array([ 5,  6,  7,  8,  9, 10, 11])

In [70]:
a = np.arange(12).reshape(3,4)
b = a>4
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [73]:
#iterating using nditer
# access the elements of an array in n order
import numpy as np
a = np.arange(20).reshape(4,5)
print(a)
print()
for x in np.nditer(a,order = 'C'): #access elements row wise, can use 'A' instead of 'C'
    print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [76]:
a = np.arange(20).reshape(4,5)
print(a)
print()
for x in np.nditer(a,order = 'F'): #access elements colum wise, can use 'K' instead of 'F'
    print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

0
5
10
15
1
6
11
16
2
7
12
17
3
8
13
18
4
9
14
19


In [78]:
a = np.arange(30).reshape(5,6) #difference between flatten and ravel is we can change order of flattening in flatten
print(a)                       # according to row or column
print()
print(a.flatten(order='C'))
print()
print(a.flatten(order='F'))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[ 0  6 12 18 24  1  7 13 19 25  2  8 14 20 26  3  9 15 21 27  4 10 16 22
 28  5 11 17 23 29]


In [79]:
a.transpose() #row<->column in a matrix

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [81]:
# changing order of the original matrix permanently
a.resize(6,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [82]:
#cummulative sum of elements
import numpy as np
a = np.arange(12).reshape(3,4)
print(a)
print()
a.cumsum(axis=1) #axis = 1 -> according to row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [83]:
a = np.arange(12).reshape(3,4)
print(a)
print()
a.cumsum(axis=0) #axis = 0 -> according to column

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [86]:
a.shape #order of matrix

(3, 4)

In [92]:
c = np.array([[[0,1,2],[10,11,12]],
             [[100,101,102],[110,111,112]]])
print(c)
c[1,...] # 1 is second element of 3 dimention matrix (... is same as :::)

[[[  0   1   2]
  [ 10  11  12]]

 [[100 101 102]
  [110 111 112]]]


array([[100, 101, 102],
       [110, 111, 112]])

In [ ]:
#study broadcast,broadcast2 and roll axis and np.roll of matrix of n order

In [18]:
import numpy as np # rotates the array or matrix according to axis
a = np.ones((2,4,5,6)) #dimention of array not elements
np.rollaxis(a,1).shape

(4, 2, 5, 6)

In [12]:
x = np.arange(10) #roll rotates the element according to position
print(x)
np.roll(x,2)

[0 1 2 3 4 5 6 7 8 9]


array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
a = np.arange(20).reshape(4,5)
print(a)
print()
np.roll(a,2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



array([[18, 19,  0,  1,  2],
       [ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17]])

In [24]:
a = np.arange(20).reshape(4,5)
print(a)
print()
np.rollaxis(a,1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [3]:
import numpy as np
a = np.arange(16).reshape(2,4,2)
print(a)
print()
np.rollaxis(a,2) # 3rd element(2position) in the order of arrays gets shifted

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]



array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14]],

       [[ 1,  3,  5,  7],
        [ 9, 11, 13, 15]]])

In [25]:
a = np.arange(20).reshape(4,5)
print(a)
print()
np.roll(a,-33) #gets the first 20 elements then again goes to start to count the remaining elements(13)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



array([[13, 14, 15, 16, 17],
       [18, 19,  0,  1,  2],
       [ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [27]:
a = np.ones((4,5,6,7,8,4)) #dimention of matrix is getting changed
np.rollaxis(a,3).shape

(7, 4, 5, 6, 8, 4)

In [33]:
#broadcast creates copies of array
import numpy as np
x = np.array([1,2,3])
np.broadcast_to(x,(6,3)) #number of columns is always equal to number of element

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [34]:
x = np.array([[1],[2],[3]]) #maps the elements according to axis
print(x)
y = np.array([4,5,6])
print(y)
b = list(np.broadcast(x,y))
for i in b:
    print(i)
print(b)

[[1]
 [2]
 [3]]
[4 5 6]
(1, 4)
(1, 5)
(1, 6)
(2, 4)
(2, 5)
(2, 6)
(3, 4)
(3, 5)
(3, 6)
[(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)]


In [36]:
x = np.arange(6).reshape(1,6)
y = np.arange(18).reshape(3,6) #atleast 1 of the row or column of the 2 matrixes must be equal (in this case column)
b = np.broadcast(x,y)
print(x)
print()
print(y)
print()
for i in b:
    print(i)

[[0 1 2 3 4 5]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 5)
(0, 6)
(1, 7)
(2, 8)
(3, 9)
(4, 10)
(5, 11)
(0, 12)
(1, 13)
(2, 14)
(3, 15)
(4, 16)
(5, 17)


In [37]:
x = np.arange(6).reshape(6,1)
y = np.arange(18).reshape(6,3)
b = np.broadcast(x,y)
print(x)
print()
print(y)
print()
for i in b:
    print(i)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]

(0, 0)
(0, 1)
(0, 2)
(1, 3)
(1, 4)
(1, 5)
(2, 6)
(2, 7)
(2, 8)
(3, 9)
(3, 10)
(3, 11)
(4, 12)
(4, 13)
(4, 14)
(5, 15)
(5, 16)
(5, 17)
